apiVersion: example.crossplane.io/v1
kind: App
metadata:
  annotations:
    terasky.backstage.io/source-info: >-
      {"pushToGit":true,"gitBranch":"main","gitRepo":"github.com?owner=benjohnson-dev&repo=kubecon-na-2025","gitLayout":"cluster-scoped","basePath":"demo-cluster/demo-app/App"}
    terasky.backstage.io/add-to-catalog: 'true'
    terasky.backstage.io/owner: group:default/guests
    terasky.backstage.io/system: demo-app
    terasky.backstage.io/source-file-url: >-
      https://github.com/benjohnson-dev/kubecon-na-2025/blob/main/demo-cluster/demo-app/App/demo-app-01.yaml
  name: demo-app-01
  namespace: demo-app
spec:
  image: nginx
  crossplane:
    compositionUpdatePolicy: Automatic
